[[corgis]]
name = "Trinket"
instagram = "https://instagram.com/trinketbaby/"

[[corgis]]
name = "Ernie"
instagram = "https://instagram.com/sirbunnybottom/"

[[corgis]]
name = "Tibby"
instagram = "https://instagram.com/tibbythecorgi/"

[[corgis]]
name = "Pudge"
instagram = "https://instagram.com/pudgethecorgi/"
