name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Cache dependencies
        run: deno cache mod.ts mod_test.ts

      - name: Run tests
        run: deno test --allow-read
